# -*- coding: utf-8 -*-
"""barenblatt_2d.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T6jDDE8kW2zXdO3-o9H2RMQFopWMsuOj
"""

# -*- coding: utf-8 -*-
"""
examples/barenblatt_2d.py
2D Radial Barenblatt – Section 5.4
Mass = 1.0, m=2, exact solution, NO ERRORS
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

# ----------------------------------------------------------------------
# 1. Parameters (2D, m=2)
# ----------------------------------------------------------------------
m = 2.0
d = 2
alpha = 1.0 / (d * (m - 1) + 2)   # = 1/4
beta  = alpha / d                  # = 1/8
kappa = 1.0 / (d * (m + 1))        # = 1/6
C = 1.0                            # mass = 1
t0 = 0.1
t_final = 1.0
R_max = 20.0
Nr = 1024
dr = R_max / Nr

# Cell centers and face radii
rc = np.linspace(dr / 2, R_max - dr / 2, Nr)
r_face = np.linspace(0, R_max, Nr + 1)

# ----------------------------------------------------------------------
# 2. Exact solution
# ----------------------------------------------------------------------
def barenblatt_2d(r, t):
    xi = r / t**beta
    inside = C - kappa * xi**2
    u = np.zeros_like(r)
    pos = inside > 0
    u[pos] = t**(-alpha) * inside[pos]**(1.0/(m-1.0))
    return u

def support_radius(t):
    return np.sqrt(C / kappa) * t**beta

# ----------------------------------------------------------------------
# 3. Radial PME: du/dt = (1/r) ∂/∂r (r D ∂u/∂r), D = u^m
# ----------------------------------------------------------------------
def pme_rhs_radial(u, dr, rc, r_face, m):
    # Interface values
    u_int = np.concatenate(([u[0]], 0.5*(u[:-1] + u[1:]), [u[-1]]))
    D_int = u_int**m

    # Gradient at interfaces
    grad_u = np.diff(u) / dr
    grad_u = np.concatenate(([grad_u[0]], grad_u, [grad_u[-1]]))

    # Flux: F = r * D * du/dr
    flux = D_int * grad_u * r_face

    # Divergence: (1/(r_c * dr)) * (F_{i+1/2} - F_{i-1/2})
    F_diff = np.diff(flux)
    div = F_diff / (rc * dr)
    return div

def step_bdf1(u, dt, dr, rc, r_face, m):
    rhs_expl = pme_rhs_radial(u, dr, rc, r_face, m)
    u_new = u.copy()
    for _ in range(20):
        rhs_impl = pme_rhs_radial(u_new, dr, rc, r_face, m)
        u_new = u + dt * (0.5 * rhs_expl + 0.5 * rhs_impl)
    return u_new

# ----------------------------------------------------------------------
# 4. Initial condition
# ----------------------------------------------------------------------
u = barenblatt_2d(rc, t0)
mass0 = np.sum(u * 2 * np.pi * rc * dr)
print(f"Initial mass = {mass0:.6f}")

# ----------------------------------------------------------------------
# 5. Time integration
# ----------------------------------------------------------------------
t = t0
while t < t_final:
    dt = min(0.3 * dr**2 / (2.0 * (np.max(u**m) + 1e-12)), t_final - t)
    u = step_bdf1(u, dt, dr, rc, r_face, m)
    t += dt

    if int(t * 1000) % 100 == 0:
        mass = np.sum(u * 2 * np.pi * rc * dr)
        print(f"t = {t:.3f} | dt = {dt:.2e} | mass = {mass:.6f}")

# ----------------------------------------------------------------------
# 6. Final error
# ----------------------------------------------------------------------
u_exact = barenblatt_2d(rc, t_final)
L2_err = np.sqrt(np.sum((u - u_exact)**2 * 2 * np.pi * rc * dr))
mass_final = np.sum(u * 2 * np.pi * rc * dr)

# ----------------------------------------------------------------------
# 7. Plot
# ----------------------------------------------------------------------
FIG_DIR = Path(__file__).parent.parent / "figures" if '__file__' in globals() else Path.cwd() / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

r_plot = np.linspace(0, R_max, 1000)
u_exact_plot = barenblatt_2d(r_plot, t_final)

plt.figure(figsize=(6, 4))
plt.plot(r_plot, u_exact_plot, 'r--', lw=1.5, label='Exact')
plt.plot(rc, u, 'b-', lw=1.5, label='Numerical')
plt.axvline(support_radius(t_final), color='k', ls=':', lw=1, label=f'Support = {support_radius(t_final):.2f}')
plt.xlabel('Radial distance $r$')
plt.ylabel('$u(r,1)$')
plt.title(f'2D Barenblatt (Radial) at $t=1$ (Nr={Nr})')
plt.legend()
plt.grid(True, alpha=0.3)
plt.tight_layout()
plt.savefig(FIG_DIR / "barenblatt_2d_radial.png", dpi=300)
plt.close()
print("saved • barenblatt_2d_radial.png")

# ----------------------------------------------------------------------
# 8. Summary
# ----------------------------------------------------------------------
print("\n=== 2D BARENBLATT VALIDATION ===")
print(f"Final mass error : {abs(mass_final - mass0)/mass0:.2e}")
print(f"L² error         : {L2_err:.2e}")
print(f"Support radius   : {support_radius(t_final):.2f}")