# -*- coding: utf-8 -*-
"""convergence_study.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G-umFpATJnZ4Xk7ObvVk7NBTbMHm98Sx
"""

# examples/convergence_study.py
import numpy as np
from pathlib import Path
import os
import matplotlib.pyplot as plt

# Reuse the same Barenblatt functions
m = 2.0
alpha = 1.0 / (m + 1.0)
beta = 1.0 / (m + 1.0)
kappa = 1.0 / (2.0 * (m + 1.0))
C = (np.pi)**(1.0/3.0) * (3.0/8.0)**(2.0/3.0)
t0, t_final = 0.1, 1.0

def barenblatt_exact(x, t):
    xi = np.abs(x) / t**beta
    inside = C - kappa * xi**2
    u = np.zeros_like(x)
    pos = inside > 0
    u[pos] = t**(-alpha) * inside[pos]**(1.0/(m-1.0))
    return u

# Reuse pme_rhs, step_bdf1, cfl_dt from barenblatt_1d.py
# (Copy them here or import if modularized)

def run_simulation(Nx, L=15.0):
    dx = 2*L / Nx
    x = np.linspace(-L, L, Nx + 1)
    xc = x[:-1] + dx/2.0
    u = barenblatt_exact(xc, t0)
    t = t0
    while t < t_final:
        dt = min(0.4 * dx**2 / (2.0 * np.max(u**m + 1e-12)), t_final - t)
        # Use step_bdf1 (copy from barenblatt_1d.py)
        rhs_expl = pme_rhs(t, u, dx, m)
        u_new = u.copy()
        for _ in range(20):
            rhs_impl = pme_rhs(t + dt, u_new, dx, m)
            u_new = u + dt * (0.5 * rhs_expl + 0.5 * rhs_impl)
        u = u_new
        t += dt
    u_exact = barenblatt_exact(xc, t_final)
    return np.sqrt(np.sum((u - u_exact)**2) * dx)

def pme_rhs(t, u, dx, m):
    u_c = u.copy()
    u_left  = np.concatenate(([u_c[0]], u_c[:-1]))
    u_right = np.concatenate((u_c[1:], [u_c[-1]]))
    u_int   = 0.5 * (u_left + u_right)
    D_int   = u_int**m
    grad_u  = (u_right - u_left) / dx
    flux    = D_int * grad_u
    flux_left  = np.concatenate(([flux[0]], flux[:-1]))
    flux_right = np.concatenate((flux[1:], [flux[-1]]))
    return (flux_right - flux_left) / dx

# Run convergence
Ns = [128, 256, 512, 1024, 2048]
errors = []
hs = []

for Nx in Ns:
    print(f"Running Nx = {Nx}...")
    err = run_simulation(Nx)
    errors.append(err)
    hs.append(2*15.0 / Nx)
    print(f"L2 error = {err:.2e}")

# Plot log-log
FIG_DIR = Path(os.getcwd()) / "figures" if '__file__' not in globals() else Path(__file__).parent.parent / "figures"
FIG_DIR.mkdir(exist_ok=True, parents=True)

plt.figure(figsize=(6,5))
plt.loglog(hs, errors, 'bo-', label='Numerical error')
plt.loglog(hs, [errors[-1]*(hs[-1]/h)**2 for h in hs], 'k--', label='O(h²)')
plt.xlabel('h = Δx')
plt.ylabel('L² error')
plt.title('Convergence Rate (1D Barenblatt)')
plt.legend()
plt.grid(True, which='both', ls=':')
plt.tight_layout()
plt.savefig(FIG_DIR / "convergence_rate.png", dpi=300)
plt.close()
print("saved • convergence_rate.png")