# -*- coding: utf-8 -*-
"""real_estate_fit.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_TduLfwh8VWLoSZrUCC0KtrTfK0mh4Vy
"""

# examples/real_estate_fit.py
"""
R-PME Calibration to NYC Housing Prices (2020–2025)
Section 10 – Urban Growth Modeling
FIXED: Bounded K, realistic prediction
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.optimize import curve_fit
from pathlib import Path
import os

# ----------------------------------------------------------------------
# 1. NYC Price Data (2020–2025) – Manhattan avg
# ----------------------------------------------------------------------
years = np.array([2020, 2021, 2022, 2023, 2024, 2025])
prices = np.array([650, 720, 810, 920, 1050, 1200])  # $k/sqft

# ----------------------------------------------------------------------
# 2. R-PME: du/dt = Δu^m + r u (1 - u/K)
#     Use bounded K (max 3000 k$/sqft)
# ----------------------------------------------------------------------
def rpme_growth(t, r, K, u0=650):
    return K / (1 + (K/u0 - 1) * np.exp(-r * t))

# Bounds: r ∈ [0,1], K ∈ [1500, 3000]
bounds = ([0.01, 1500], [1.0, 3000])
popt, _ = curve_fit(rpme_growth, years - 2020, prices, p0=[0.15, 2500], bounds=bounds)
r_fit, K_fit = popt

# ----------------------------------------------------------------------
# 3. Prediction to 2030
# ----------------------------------------------------------------------
t_future = np.linspace(2020, 2030, 200)
u_pred = rpme_growth(t_future - 2020, r_fit, K_fit)

# ----------------------------------------------------------------------
# 4. Figure directory
# ----------------------------------------------------------------------
if '__file__' in globals():
    FIG_DIR = Path(__file__).resolve().parent.parent / "figures"
else:
    FIG_DIR = Path(os.getcwd()) / "figures"
FIG_DIR.mkdir(parents=True, exist_ok=True)

# ----------------------------------------------------------------------
# 5. Plot
# ----------------------------------------------------------------------
plt.figure(figsize=(7, 5))
plt.plot(years, prices, 'ro', markersize=8, label='Observed (Zillow)')
plt.plot(t_future, u_pred, 'b-', linewidth=2, label=f'R-PME Fit (r={r_fit:.3f}, K={K_fit:.0f})')
plt.axhline(K_fit, color='k', linestyle='--', alpha=0.6, label='Carrying Capacity')
plt.axvline(2025, color='gray', linestyle=':', alpha=0.7)
plt.xlabel('Year')
plt.ylabel('Price ($k/sqft)')
plt.title('NYC Housing Price Growth – R-PME Calibration')
plt.legend()
plt.grid(True, alpha=0.3)
plt.ylim(500, 3200)
plt.tight_layout()
plt.savefig(FIG_DIR / "urban_growth_nyc.png", dpi=300, bbox_inches='tight')
plt.close()
print("saved • urban_growth_nyc.png")

# ----------------------------------------------------------------------
# 6. Summary
# ----------------------------------------------------------------------
print("\n=== R-PME REAL ESTATE FIT ===")
print(f"  Growth rate r = {r_fit:.4f} /yr")
print(f"  Carrying capacity K = {K_fit:.0f} k$/sqft")
print(f"  2025 Price (observed) = {prices[-1]:.0f} k$/sqft")
print(f"  2030 Prediction = {u_pred[-1]:.0f} k$/sqft")